pid logs/sitio1.pid;
events {
	worker_connections 1024;
}
http {
	server {
		listen 81;

		location / {
			root "/mnt/c/Users/Asus TUF F17/Documents/FundamentosWeb/17289/nginx/3sitios/sitio1";
			index index.html;
		}
	}
}
