pid logs/sitio2.pid;
events {
	worker_connections 1024;
}
http {
	server {
		listen 82;

		location / {
			root "/mnt/c/Users/Asus TUF F17/Documents/FundamentosWeb/17289/nginx/3sitios/sitio2";
			index index.html;
		}
	}
}
